---
  users:
    - '<gmailuser@gmailid.com>'
  attendees:
    - '<gmailuser1@gmailid.com>'
  time_zone: 'America/Los_Angeles'
  start_date: '2020-02-12' #yyyy-mm-dd format
  end_date: 2020-05-12' #yyyy-mm-dd format
  meeting_duration: 60
  recurrence:
    - '01:00 PM'
    - '02:00 PM'
  single_instance:
    - '01:00 AM'
    - '02:00 AM'
    - '03:00 AM'
    - '04:00 AM'
    - '05:00 AM'
    - '06:00 AM'
    - '07:00 AM'
    - '08:00 AM'
    - '09:00 AM'
    - '10:00 AM'
    - '11:00 AM'
    - '12:00 PM'
    - '03:00 PM'
    - '04:00 PM'
    - '05:00 PM'
    - '06:00 PM'
    - '07:00 PM'
    - '08:00 PM'
    - '09:00 PM'
    - '10:00 PM'
